spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech_dev
    username: fintech_dev
    password: fintech_dev_password
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.fintech: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
